export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-black px-6 py-16 max-w-2xl mx-auto">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: March 9, 2026</p>

      <div className="space-y-6 text-sm text-gray-700 leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-black mb-2">Acceptance of terms</h2>
          <p>
            By using Loop, you agree to these terms. If you do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-black mb-2">What Loop provides</h2>
          <p>
            Loop is a personalized briefing service. It reads your Google Calendar events from the
            past 3–6 months to build your persona using AI, then delivers a daily morning briefing
            with relevant news, local events, and activity suggestions. Loop may also add suggested
            events to your Google Calendar with your explicit consent.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-black mb-2">Google Calendar access</h2>
          <p>
            By connecting your Google account, you grant Loop permission to read your calendar
            events and create new events on your behalf. You can revoke this access at any time
            through your{' '}
            <a href="https://myaccount.google.com/permissions" target="_blank" rel="noopener noreferrer" className="underline hover:text-black">
              Google Account Permissions
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-black mb-2">Event recommendations</h2>
          <p>
            Event recommendations are generated by AI and may not always be accurate. Loop does
            not guarantee the accuracy, availability, or quality of recommended events. Always
            verify event details before attending.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-black mb-2">User responsibilities</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>You are responsible for your Google account credentials</li>
            <li>Do not misuse the service or attempt to access other users' data</li>
            <li>You must be at least 18 years old to use Loop</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-black mb-2">Limitation of liability</h2>
          <p>
            Loop is provided "as is" without warranties of any kind. We are not liable for any
            damages arising from your use of the service, including but not limited to inaccurate
            event recommendations, missed events, or calendar modifications.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-black mb-2">Changes to terms</h2>
          <p>
            We may update these terms at any time. Continued use of Loop after changes constitutes
            acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-black mb-2">Contact</h2>
          <p>
            For questions about these terms, contact us at omorke@gmail.com.
          </p>
        </section>
      </div>

      <div className="mt-12 pt-6 border-t border-gray-100">
        <a href="/" className="text-sm text-gray-400 hover:text-black transition-colors">← Back to Loop</a>
      </div>
    </div>
  );
}
